### ISSUE TITLE
Backward facing trackers?

### ISSUE THREAD

**Issue by HexHyte** [KinectToVR/Amethyst-Releases#1]
After the calibration the trackers have been placed in the correct places but they were all facing in the opposite direction.
I had to manually flip every tracker by setting a 180° rotation, this completely resolved the issue.
This also happens by using the official stable K2VR release.

**Comment by TripingPC** [comment]
That's what offsets are for. Only Blade & Sorcery requires this, every other game works fine no matter the tracker orientation. Other than that, they're meant to align joints with rotation overrides.
