### ISSUE TITLE
decimal point other than dot has issues

### ISSUE THREAD

**Issue by HidingCherry** [KinectToVR/Amethyst-Releases#14]
I use a German environment.
Basically not an issue, but Amethyst is a bit special with overrides and the decimal point.

In German we use a comma as a decimal point, while the English languages use a dot.
Hence - if I use a dot put in a "floating point" value (programmer knows), it automatically assumes that it shouldn't be a "0.02" but instead interprets it as a "2".
I have to use a comma "0,02" - which afterwards is shown as "0.02" but is interpreted correctly as a floating point value.

Changing the value with up/down arrows is scary, because it tries to higher from the "0.02" and suddenly it is "3", then "10" etc - it completely goes crazy.

**Comment by meruune** [comment]
I’m sorry, but it would either be needed to write custom formatters for offsets ComboBoxes or parse the values manually. Other than that, opening an issue at https://github.com/CommunityToolkit/WindowsCommunityToolkit could certainly be *something*, I doubt they’re going to do anything about that though.

I’ll see if rewriting current code to use C#’s builtin regional formatting would be bearable, but no promises here (it’s already a miracle that offsets don’t crash the whole app…..)

**Comment by meruune** [comment]
The fix will be included in an upcoming update, closing for now

https://github.com/KinectToVR/Amethyst-Releases/assets/50022719/02209593-4aae-4da6-92c9-7006e5c299c8

**Comment by HidingCherry** [comment]
Very nice, thanks!
