### ISSUE TITLE
Installation Failure Due to Space in Destination Path

### ISSUE THREAD

**Issue by Elteeb96** [KinectToVR/Amethyst-Releases#2]
I am going through the process of getting Amethyst installed and it is stalling on the "registering SteamVR Addon" section. I have determined that it is a result of the space in the installation path. Thinking about it, if this issue is present in this step, any other subsequent steps using the same path would also likely fail. 

I would prefer to not have it in the root directory for organizations sake. (Though I have done it for the sake of testing)

Error message for reference.
`F20220918 11:29:02.143900 13148 OpenVRUtil.Drivers.cs::RegisterSteamVrDriver:50] vrpathreg failed:
	Code: -2
	Args: "adddriver D:\Program Files\Amethyst\Amethyst"`

Let me know if you need any other log information, though I think the cause for this issue is fairly straight forward.

**Comment by hyblocker** [comment]
As a temporary work around, open the installer with the `--debug` launch argument, press the `F12` key to enter the debug menu, then click the disable vrpathreg button. Then click back and proceed with a regular install.

**Comment by KimihikoAkayasaki** [comment]
The current version doesn't support wide paths, please make sure you've installed it in a path like `C:\\Amethyst`.
(Without above-ASCII characters e.g. `❣`, `あいうえお`, etc)
As for absolute/relative handling... maaan I'm not really *that* dumb

**Comment by hyblocker** [comment]
> I am going through the process of getting Amethyst installed and it is stalling on the "registering SteamVR Addon" section. I have determined that it is a result of the space in the installation path. Thinking about it, if this issue is present in this step, any other subsequent steps using the same path would also likely fail.
> 
> I would prefer to not have it in the root directory for organizations sake. (Though I have done it for the sake of testing)
> 
> Error message for reference. `F20220918 11:29:02.143900 13148 OpenVRUtil.Drivers.cs::RegisterSteamVrDriver:50] vrpathreg failed: Code: -2 Args: "adddriver D:\Program Files\Amethyst\Amethyst"`
> 
> Let me know if you need any other log information, though I think the cause for this issue is fairly straight forward.

Fixed internally; fix will be pushed in next update.
