### ISSUE TITLE
help

### ISSUE THREAD

**Issue by sidthecat454** [KinectToVR/Amethyst-Releases#7]
cannot download kinect 360 drivers does not install

**Comment by Stiggimy** [comment]
Manually installing the SDKs should do the job.

Here's the link for the Xbox 360 Kinect: https://download.microsoft.com/download/E/1/D/E1DEC243-0389-4A23-87BF-F47DE869FC1A/KinectSDK-v1.8-Setup.exe

If you're using Xbox One Kinect then you should follow the instructions on the Amethyst docs (https://docs.k2vr.tech/en/one/troubleshooting/#drivers).

You can join our Discord server: https://discord.gg/27TBPCZPfn
