### ISSUE TITLE
Manual Calibration not responding to controller input

### ISSUE THREAD

**Issue by Krzeszny** [KinectToVR/Amethyst-Releases#9]
You can blame it on WMR or SteamVR but this function is unusable for me. 

I've tried both desktop modes and in manual calibration (for example for waist trackers), moving the joysticks on the controllers doesn't rotate or move the trackers. I remember it used to work but I can't make it work anymore.

I'm using Amethyst v1.2.5.0 from GitHub.

**Comment by KimihikoAkayasaki** [comment]
For SteamVR bindings, and therefore manual calibration to work, the desktop overlay needs to be closed. In short, you need to be in the SteamVR compositor space, with all overlays closed.

Please read [the docs](https://docs.k2vr.tech) before opening another pointless issue on GitHub. You can also access some app-related docs from within the help button.

**Comment by Krzeszny** [comment]
> For SteamVR bindings (and therefore manual calibration, too) to work, the menu overlay needs to be closed. In short, you need to be in the SteamVR compositor space, with all overlays closed.

I'm not sure what you mean by "compositor space" (I've actually googled it and no description came up, only people reporting bugs with the "VR compositor"). Also, I've followed the manual calibration tutorial in the docs.

Well, the trackers don't respond to controller input even in the circular grid/aurora borealis area with Steam/WMR desktop overlays closed. We can discuss it on Discord but me being me, I just wanted to prove this issue isn't pointless (or that I can't follow instructions for some reason).

**Comment by KimihikoAkayasaki** [comment]
Using the "old bindings menu" within SteamVR, please verfiy that WMR bindings for Amethyst exist, are valid, and active. Amethyst cannot manage the bindings besides providing them, and listening to chords or actions - so as long as they work for any other platform, it's a matter of particular bindings, be it errors in our JSON or incorrectly set up SteamVR settings. I won't be responding to this issue further, and you don't need to "prove" anything to anyone, even we are still only barely here.

**Comment by Krzeszny** [comment]
In case anyone else has this problem: I'm not sure what fixed I don't have this issue anymore.
